In [1]:
import numpy as np

# 1 求平均值

`np.mean(ndarray,axis = ...)`

`ndarray.mean(axis = ...)`

axis = 0: 纵向计算平均值

axis = 1: 横向计算平均值


In [2]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
print(a.mean(axis=0))
print(a.mean(axis=1))
print(np.mean(a))

[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]
9.5


# 2 求中位数

`np.median()`


In [4]:
a = np.arange(20).reshape(4, 5)

print(np.median(a, axis=0))
print(np.median(a, axis=1))
print(np.median(a))

[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]
9.5


# 3 求标准差

`np.std(ndarray,axis = ...) / ndarray.std(axis = ...)`


In [5]:
a = np.arange(20).reshape(4, 5)

# 逐列求
print(np.std(a, axis=0))

# 逐行求
print(a.std(axis=1))

# 对整个二维数组求
print(a.std())

[5.59016994 5.59016994 5.59016994 5.59016994 5.59016994]
[1.41421356 1.41421356 1.41421356 1.41421356]
5.766281297335398


# 4 方差

`np.var(ndarray,axis = ...) / ndarray.var(axis = ...)`


In [6]:
a = np.arange(20).reshape(4, 5)

# 逐列求
print(np.var(a, axis=0))

# 逐行求
print(a.var(axis=1))

# 对整个二维数组求
print(a.var())

[31.25 31.25 31.25 31.25 31.25]
[2. 2. 2. 2.]
33.25


# 5 求最大值/最小值

`np.max(ndarray,axis = ...) / ndarray.max(axis = ...)`


# 6 求和

`ndarray.sum(axis = ...) / np.sum(ndarray, axis = ...)`


# 7 加权平均值

`np.average(ndarray, axis = ..., weights = ..., returned = False)`

returned = True 则会返回权重加和的值


In [7]:
a = np.arange(20).reshape(4, 5)
w = [1, 2, 3, 4, 5]
np.average(a, axis=1, weights=w)

array([ 2.66666667,  7.66666667, 12.66666667, 17.66666667])